/*
 * @Author: tohsaka888
 * @Date: 2022-09-05 10:10:55
 * @LastEditors: tohsaka888
 * @LastEditTime: 2022-09-05 15:39:05
 * @Description: 请填写简介
 */
import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import "antd/dist/antd.css"; // or 'antd/dist/antd.less'
import { Layout } from "antd";
import Header from "components/Header";
import { useRouter } from "next/router";

function MyApp({ Component, pageProps }: AppProps) {
  const { pathname } = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {pathname !== "/" ? (
        <Layout>
          <Header />
          <Component {...pageProps} />
        </Layout>
      ) : (
        <Component {...pageProps} />
      )}
    </>
  );
}

export default MyApp;
